### ISSUE TITLE
Repeated Message Publishing Failure With StateTransitionError Errors

### ISSUE THREAD

**Issue by josephpm5** [gmr/aiorabbit#10]
I have a long running app that publishes messages to rabbitmq through the publish method of an aiorabbit.client.Client. At some point a StateTransitionError occurs, **and keeps occurring endlessly unless the whole app is restarted**.

The specific error message from the StateTransitionError is: **Invalid state transition from 'Closed' to 'Message Published'.**

This error seems to suggest that the connection maintained by aiorabbit to the rabbitmq servers has been terminated, and that publishing messages on such a closed connection is invalid.

Reading the aiorabbit docs, it sounds like part of the functionality of this library is to manage channels and connections, reconnecting in the case of errors and disconnects. However, there are some other parts of the docs that seem to suggest that things might not continue in the case of some connection related errors. This leads me to believe that there is either a bug in aiorabbit or that automatically managing connection errors and disconnects is not a feature of aiorabbit, and I misunderstood the docs thinking that it was.

For further context, here are the main DEBUG level logs around the aiorabbit client that highlight the issue:

```
Oct 29 17:48:51 ip-00-000-000-000 app/latest/00000000[0000]: [2021-10-29 17:48:51,237] DEBUG aiorabbit.client: Writing frame: <Basic.Publish object at 0x7f18e64b7de0>

Oct 29 17:48:51 ip-00-000-000-000 app/latest/000000000[0000]: [2021-10-29 17:48:51,237] WARNING asyncio: socket.send() raised exception.

Oct 29 17:48:51 ip-00-000-000-000 app/latest/000000000[0000]: [2021-10-29 17:48:51,237] DEBUG aiorabbit.client: Writing frame: <pamqp.header.ContentHeader object at 0x7f18e7de6a50>

Oct 29 17:48:51 ip-00-000-000-000 app/latest/0000000000[0000]: [2021-10-29 17:48:51,237] WARNING asyncio: socket.send() raised exception.

Oct 29 17:48:51 ip-00-000-000-000 app/latest/0000000000[0000]: [2021-10-29 17:48:51,237] DEBUG aiorabbit.client: Writing frame: <pamqp.body.ContentBody object at 0x7f18e7de6a90>

Oct 29 17:48:51 ip-00-000-000-000 app/latest/0000000000[0000]: [2021-10-29 17:48:51,237] WARNING asyncio: socket.send() raised exception.

Oct 29 17:48:51 ip-00-000-000-000 app/latest/00000000000[0000]: [2021-10-29 17:48:51,237] DEBUG aiorabbit.client: Set state to 257: Message Published while state is 259: Closed -
{}
[None]

Oct 29 17:48:51 ip-00-000-000-000 app/latest/00000000000[0000]: [2021-10-29 17:48:51,237] ERROR app: Unexpected error when trying to publish AMQP message: Invalid state transition from 'Closed' to 'Message Published'

```

**Comment by gmr** [comment]
This looks like expected behavior.
