### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by frostpuppet** [gmr/aiorabbit#11]
I can't really seem to find it but is there a way to connect to use a cacertfile, certfile, keyfile?

Ive seen this functionality in pika
https://pika.readthedocs.io/en/stable/examples/tls_mutual_authentication.html
https://pika.readthedocs.io/en/stable/examples/tls_server_authentication.html

**Comment by gmr** [comment]
Sorry for the very long delay in a reply and I assume you've moved on. For any others looking, this is now available by passing a ssl.SSLContext into the connect methods or the Client construction.
