### ISSUE TITLE
"No heartbeat" message reports wrong number of seconds

### ISSUE THREAD

**Issue by nvllsvm** [gmr/aiorabbit#8]
Running the below script results in a "No heartbeat" message with an incorrect seconds value: a duration much longer than the lifetime of either the script or container.

**Output**
```
sleeping
wake up
No heartbeat in 16881.569499 seconds
```

**Script**
```python
"""
used the following to run rabbitmq:
    docker run --rm --net=host rabbitmq:management-alpine
"""
import asyncio
import time

import aiorabbit
import aiorabbit.client


async def main():
    # works fine
    client = aiorabbit.client.Client('amqp://guest:guest@localhost:5672/%2f?heartbeat=5')
    await client.connect()

    await client.publish(exchange='amq.direct', routing_key='test',
                         message_body='hello')

    print('sleeping')
    time.sleep(10)
    print('wake up')

    await client.publish(exchange='amq.direct', routing_key='test',
                         message_body='hello')


if __name__ == '__main__':
    asyncio.run(main())
```

**Notes**
- **OS:** Arch Linux
- **System Timezone:** `America/New_York`
- **Container Timezone:** `UTC`
- **Python:** 3.9.5
- **aiorabbit:** 1.0.0a1

Changing the container's timezone to match the local machine's has no noticeable impact on the incorrect duration in the output.

**Comment by gmr** [comment]
This is due to sleeping before the first heartbeat. Will disable the check when the last heartbeat value is in the initial value of `0`

**Comment by gmr** [comment]
Will be resolved in the next release
